import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { Bookmark, LogOut, Map, PlaneTakeoff, Sparkles, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Wordmark } from "@/components/layout/Wordmark";
import type { PublicUser } from "@/lib/auth/types";
import { authApi } from "@/services/authService";
import heroCoast from "@/assets/hero-coast.jpg";

export const Route=createFileRoute("/account")({head:()=>({meta:[{title:"Your ASTERA"}]}),component:AccountPage});
function AccountPage(){const navigate=useNavigate();const [user,setUser]=useState<PublicUser|null>(null);useEffect(()=>{authApi.me().then(({user})=>{if(!user)void navigate({to:"/login"});else setUser(user)})},[navigate]);if(!user)return <main className="grid min-h-screen place-items-center bg-ink text-white">Loading your ASTERA…</main>;return <main className="min-h-screen bg-[#061827] px-4 py-6 text-white"><section className="mx-auto max-w-5xl"><header className="flex items-center justify-between"><Wordmark withMark signature/><div className="flex items-center gap-3">{user.avatarUrl?<img src={user.avatarUrl} alt="" className="h-10 w-10 rounded-full"/>:<span className="grid h-10 w-10 place-items-center rounded-full bg-white/10"><UserRound/></span>}<Button variant="outline" size="sm" className="border-white/20 bg-transparent text-white hover:bg-white hover:text-ink" onClick={async()=>{await authApi.logout();await navigate({to:"/"})}}><LogOut/>Log out</Button></div></header><div className="mt-14"><p className="text-xs tracking-[.18em] text-teal uppercase">You’re in</p><h1 className="mt-2 font-serif-display text-5xl">Welcome, {user.name.split(" ")[0]} 👋</h1><p className="mt-2 text-white/60">Ready to plan your next unforgettable trip?</p></div><article className="relative mt-8 overflow-hidden rounded-[1.6rem] border border-white/10"><img src={heroCoast} alt="Mountain and coast destination" className="h-64 w-full object-cover opacity-55"/><div className="absolute inset-0 bg-gradient-to-r from-ink/90 to-transparent"/><div className="absolute inset-0 flex max-w-lg flex-col justify-center p-8"><h2 className="font-serif-display text-3xl">Start a new trip</h2><p className="mt-2 text-sm text-white/65">Tell us the constraints. ASTERA will find the strongest answer.</p><Button asChild variant="hero" className="mt-6 w-fit"><Link to="/plan"><PlaneTakeoff/>Plan my trip</Link></Button></div></article><div className="mt-8 grid gap-4 sm:grid-cols-3"><DashLink to="/saved" icon={<Bookmark/>} title="Your trips" detail="Open saved itineraries"/><DashLink to="/results" icon={<Map/>} title="Explore" detail="Review recommendations"/><DashLink to="/onboarding" icon={<Sparkles/>} title="Travel style" detail={`${user.profile.interests.length||"No"} interests selected`}/></div></section></main>}
function DashLink({to,icon,title,detail}:{to:"/saved"|"/results"|"/onboarding";icon:React.ReactNode;title:string;detail:string}){return <Link to={to} className="rounded-3xl border border-white/10 bg-white/[.06] p-6 transition hover:-translate-y-1 hover:bg-white/[.1]"><span className="text-teal">{icon}</span><h2 className="mt-5 font-serif-display text-2xl">{title}</h2><p className="mt-1 text-xs text-white/55">{detail}</p></Link>}
