import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, Eye, EyeOff } from "lucide-react";
import { useState } from "react";
import { SsoButtons } from "@/components/auth/SsoButtons";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Wordmark } from "@/components/layout/Wordmark";
import { authApi } from "@/services/authService";
import heroEditorial from "@/assets/hero-editorial.jpg";

export const Route = createFileRoute("/login")({ validateSearch:(search:Record<string,unknown>)=>({error:typeof search.error==="string"?search.error:""}), head:()=>({meta:[{title:"Log in — ASTERA"}]}), component: LoginPage });
const oauthError:Record<string,string>={"sso-not-configured":"This sign-in provider has not been configured yet.","sso-cancelled":"Sign in was cancelled.","sso-failed":"The provider could not complete sign in. Please try again."};
function LoginPage(){const navigate=useNavigate();const {error:searchError}=Route.useSearch();const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState(oauthError[searchError]??"");return <main className="relative grid min-h-screen place-items-center overflow-hidden bg-ink px-4 py-10 text-white"><img src={heroEditorial} alt="Mountain destination at dusk" className="absolute inset-0 h-full w-full object-cover opacity-35"/><div className="absolute inset-0 bg-gradient-to-b from-[#03101f]/70 to-[#03101f]/95"/><Link to="/" className="absolute top-6 left-6 z-10 grid h-10 w-10 place-items-center rounded-full border border-white/15 bg-white/10" aria-label="Back"><ArrowLeft/></Link><section className="relative w-full max-w-md rounded-[1.75rem] border border-white/15 bg-[#061827]/90 p-7 shadow-2xl backdrop-blur-xl sm:p-10"><Wordmark withMark signature className="text-white"/><h1 className="mt-12 font-serif-display text-4xl">Welcome back</h1><p className="mt-2 text-sm text-white/60">Log in to continue your adventures.</p><form className="mt-7 space-y-3" onSubmit={async(e)=>{e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{const {user}=await authApi.login({email:String(f.get("email")),password:String(f.get("password"))});await navigate({to:user.profile.completed?"/account":"/onboarding"});}catch(err){setError(err instanceof Error?err.message:"Could not log in.");}finally{setBusy(false);}}}><Input name="email" type="email" required autoComplete="email" placeholder="Email address" className="h-12 rounded-xl border-white/20 bg-transparent text-white placeholder:text-white/45"/><label className="relative block"><Input name="password" type={show?"text":"password"} required autoComplete="current-password" placeholder="Password" className="h-12 rounded-xl border-white/20 bg-transparent pr-12 text-white placeholder:text-white/45"/><button type="button" onClick={()=>setShow(!show)} className="absolute top-0 right-0 grid h-12 w-12 place-items-center text-white/70">{show?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></label>{error&&<p role="alert" className="rounded-xl bg-red-400/10 p-3 text-xs text-red-200">{error}</p>}<Button type="submit" variant="hero" className="h-12 w-full rounded-xl" disabled={busy}>{busy?"Logging in…":"Log in"}</Button></form><div className="my-6 flex items-center gap-3 text-[10px] text-white/45"><span className="h-px flex-1 bg-white/15"/>OR<span className="h-px flex-1 bg-white/15"/></div><div className="[&_a]:border-white/20 [&_a]:bg-transparent [&_a]:text-white [&_a:hover]:bg-white [&_a:hover]:text-ink"><SsoButtons/></div><p className="mt-8 text-center text-sm text-white/60">Don’t have an account? <Link to="/signup" className="font-semibold text-teal">Sign up</Link></p></section></main>}
