import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Heart, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Wordmark } from "@/components/layout/Wordmark";
import type { PublicUser, TravelProfile } from "@/lib/auth/types";
import { cn } from "@/lib/utils";
import { authApi } from "@/services/authService";

export const Route=createFileRoute("/onboarding")({head:()=>({meta:[{title:"Personalise ASTERA"}]}),component:OnboardingPage});
const interests=["Adventure","Culture","Food","Relaxation","Nature","City life","Photography","Nightlife"];
function OnboardingPage(){const navigate=useNavigate();const [user,setUser]=useState<PublicUser|null>(null);const [selected,setSelected]=useState<string[]>([]);const [pace,setPace]=useState<TravelProfile["pace"]>("balanced");const [stay,setStay]=useState<TravelProfile["stayStyle"]>("mid-range");const [diet,setDiet]=useState("No preference");const [busy,setBusy]=useState(false);useEffect(()=>{authApi.me().then(({user})=>{if(!user)void navigate({to:"/login"});else{setUser(user);setSelected(user.profile.interests);setPace(user.profile.pace);setStay(user.profile.stayStyle);setDiet(user.profile.diet);}})},[navigate]);if(!user)return <main className="grid min-h-screen place-items-center bg-[#f7f4ee]">Loading…</main>;const save=async()=>{setBusy(true);await authApi.profile({interests:selected,pace,stayStyle:stay,diet,completed:true});await navigate({to:"/account"});};return <main className="grid min-h-screen place-items-center bg-[#f7f4ee] px-4 py-10"><section className="w-full max-w-xl rounded-[1.8rem] border border-border/60 bg-white p-7 text-center shadow-[0_28px_80px_-48px_rgba(3,26,39,.4)] sm:p-10"><Wordmark withMark signature/><span className="mx-auto mt-9 grid h-16 w-16 place-items-center rounded-full bg-teal/10 text-teal"><Heart className="h-7 w-7"/></span><h1 className="mt-5 font-serif-display text-4xl leading-none">Help ASTERA learn<br/>your travel style</h1><p className="mx-auto mt-3 max-w-sm text-sm text-muted-foreground">The more you share, the better your recommendations.</p><Choice title="I travel for…" values={interests} selected={selected} onClick={(value)=>setSelected(selected.includes(value)?selected.filter((item)=>item!==value):[...selected,value])}/><Choice title="My travel pace" values={["relaxed","balanced","fast"]} selected={[pace]} onClick={(value)=>setPace(value as TravelProfile["pace"])}/><Choice title="I prefer to stay in…" values={["budget","mid-range","luxury"]} selected={[stay]} onClick={(value)=>setStay(value as TravelProfile["stayStyle"])}/><Choice title="Dietary preferences" values={["No preference","Halal","Vegetarian","Vegan","Gluten-free"]} selected={[diet]} onClick={setDiet}/><Button variant="hero" className="mt-8 h-12 w-full rounded-xl" onClick={save} disabled={busy}><Sparkles/>{busy?"Saving…":"Save & continue"}</Button><button type="button" className="mt-4 text-xs text-muted-foreground hover:text-ink" onClick={save}>Skip for now</button><p className="mt-5 text-[10px] text-muted-foreground">You can update this anytime in your profile.</p></section></main>}
function Choice({title,values,selected,onClick}:{title:string;values:string[];selected:string[];onClick:(value:string)=>void}){return <fieldset className="mt-7 text-left"><legend className="text-xs font-semibold">{title}</legend><div className="mt-3 flex flex-wrap gap-2">{values.map((value)=><button key={value} type="button" onClick={()=>onClick(value)} className={cn("rounded-full border px-4 py-2 text-xs capitalize transition",selected.includes(value)?"border-teal bg-ink text-white":"border-border bg-[#faf8f3] hover:border-teal")}>{value}</button>)}</div></fieldset>}
